### ISSUE TITLE
🐞 Remove eslint disable for useEffect on JointKeySelectStep.ts:72

### ISSUE THREAD

**Issue by lprichar** [microsoft/electionguard-ui#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The eslint warning on line 72 of JointKeySelectStep.ts says that the `ceremonyClient` hook should be included in the dependencies array for `useEffect`.  However, when you include it, then React creates an infinite loop of calls to `ceremonyClient.find`:

![image](https://user-images.githubusercontent.com/1769905/152804589-720b9319-60db-4de3-94fd-432d512342cc.png)

The infinite loop does not occur if the call to `ceremonyClient.find` doesn't `setKeyCeremonies`.  Also the infinite loop does occur if you pass in pretty much any value into the dependencies list, not just `ceremonyClient`.

Remove the eslint disable and fix the underlying problem so the infinite loop doesn't occur.

### Environment

```markdown
- OS:
```

**Comment by colleenirt** [comment]
This will not be worked or considered for 1.0.  A new issue will be created if needed in the future.
