### ISSUE TITLE
🐞 Limit Keys Available in Election Setup Wizard

### ISSUE THREAD

**Issue by lprichar** [microsoft/electionguard-ui#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the selection guardian list of the election setup wizard only show ceremonies that have a public key

### Expected Behavior

If you create a key ceremony via setup joint keys and immediately go to manage joint keys, it should not be listed on the dropdown yet, because no guardians have accepted their invite and no key has been generated

### Environment

```markdown
- OS:
```

**Comment by colleenirt** [comment]
This will not be worked or considered for 1.0.  A new issue will be created if needed in the future.
