### ISSUE TITLE
Spacing Issues on Ordered List

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-ui#39]
![Screen Shot 2021-07-08 at 4 23 39 PM](https://user-images.githubusercontent.com/10125297/124985865-ec139a80-e008-11eb-9b64-0e30d455747b.png)

Two Issues:
- Text should be padded on top to ensure it lines up with numbers. 
- Bottom of list should have built in padding to ensure scrolling has room.

**Comment by deepto98** [comment]
@keithrfung H,i I just discovered this project and would like to work on this issue, can you assign this to me?

**Comment by alceil** [comment]
Can i work on this issue?

**Comment by keithrfung** [comment]
@alceil you can take this one. Just because the other one @deepto98 has is pretty large. Feel free to ask for reassignment though.

**Comment by alceil** [comment]
Okay

**Comment by keithrfung** [comment]
No longer relevant
