### ISSUE TITLE
✨  Migrate Navigation from Library to Admin App

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-ui#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

- Add `react-router` to `admin-app`
- Add a `routes` folder with a file called `MainRoutes.tsx`
- Migrate the `routes` folder from `library` to `admin-app` to keep this card simple, the actual pages can be made as blank pages in the `admin-app` instead of migrating those.

**Comment by deepto98** [comment]
@keithrfung I'd like to work on this issue, can you assign this to me?

**Comment by alceil** [comment]
I would like to work on this issue.

**Comment by keithrfung** [comment]
@deepto98 Gonna assign this to @alceil to spread out the issues.

**Comment by alceil** [comment]
Thanks

**Comment by alceil** [comment]
I have done the required changes please have a look @keithrfung
