### ISSUE TITLE
✨ Election List

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-ui#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Create a list of elections. This should just be the name of the election and a section of that allows for buttons. This page is mostly created and can be utilized to simplify this. This should be hooked up to the Menu Page. 

### Anything else?

**PERMISSIONS**
Only Admins should be able to see this page.

**Comment by lprichar** [comment]
I believe this was implemented by PR #106, please re-open if I am incorrect
